[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_staking_blog = "DJUvUmSc7JTvRDcLDXJSF97PsvenuBSTi6WUWJLQvuqt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/mitim/.config/solana/programs/solana-token-staking.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
