[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_staking_blog = "7MHr6ZPGTWZkRk6m52GfEWoMxSV7EoDjYyoXAYf3MBwS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/sidharth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
